### ISSUE TITLE
Question about query used for template 

### ISSUE THREAD

**Issue by CesarCapillas** [jpotts/share-site-space-templates#3]
Hi @jpotts:

First of all, thanks for the addon, it's a very nice and useful component. 
I'm testing it with Alfresco 5.0.2.5 version. I have a question regarding the query used in the module. 

I use several site dashboards defined in presets.xml. In particular, I defined two site / presets / space templates:
-  Collaboration Site --> "site-dashboard"
-  ZK Site --> "zk-site-dashboard"

creating the corresponding folder structure in Space Templates.

I found some strange behaviour regarding the query for copying the template. 
Sometimes I found that "zk-site-dashboard" is *\* always *\* found as the space template (for both site types) - so I found problems when creating "Collaboration Sites". 

Maybe this is related with the query:

 String query = "+PATH:\"/app:company_home/app:dictionary/app:space_templates/*\" +@cm\:name:\"" + sitePreset + "\"";

Some notes:
- If I search "site-dashboard" (or @cm:name:"site-dashboard") in Alfresco search, I found two hits in the resultset (maybe is it appropiate to use = operator for getting an exact term?). 
- There is no problem with ZK Site (zk-site-dashboard) creation in any case. 
- In the case of Collaboration Site creation it seems to get the first hit of the resultset, and I think that the query is using some relevance criteria (so the result can change). 
- Finally, I found that if I delete site-dashboard space template and I create a "Collaboration Site" it uses zk-site-dashboard template directly. 

I understand too, that a walkaround is just to rename the custom presets like "template-site-zk", avoiding collisions, between site name presets. 

Could you confirm this behaviour ?

Best regards and thanks in advance.

--C.

**Comment by jpotts** [comment]
Thanks for reporting this, I'm looking into it.

**Comment by jpotts** [comment]
I cannot recreate this on 5.0.d. Here is what I did...
I already had a space template named site-dashboard (matches the default) with several folders. I created six additional presets named:
- aaa-site-dashboard
- bbb-site-dashboard
- ccc-site-dashboard
- site-dashboard-aaa
- site-dashboard-bbb
- site-dashboard-ccc

I then created a matching entry in Data Dictionary/Space Templates for all but ccc-site-dashboard and site-dashboard-ccc.

In each space template I placed one uniquely named folder so that it could be traced back to its source.

I was then able to create sites using all six presets. The four with existing space templates were created with the proper folders from the proper templates. The two with missing space templates were created with no folders.

If I go into the Alfresco node browser and run the Lucene search, I can unambiguously find all of my space templates using the query from the source code. When you are testing this, make sure to change the syntax to "Lucene" to match what the code does. If you leave it set to "Alfresco FTS" you will see ambiguous results unless you remove the + ("plus") signs and use "AND" instead.

So this appears to not be a problem. Perhaps your folders are not being indexed by Solr by the time you are creating your site.

**Comment by CesarCapillas** [comment]
Thanks for your reply and testing Jeff. Really appreciated.

I would say it is not easy for me to debug it, even to recreate it exactly (I explain myself a little more later).

What I'm trying to say is that, I have problems with the default template (site-dashboard), not with the "new" ones, due the type of search, based on @cm:name

The new templates are found because there is no collision when trying to find the template. Only when trying to apply / search the default template "site-dashboard" you may obtain more than 1 result in the search and so my issue (because it is not an exact term search and the name of the template is tokenised - this is what I think). I imagine that if there is some relevance criteria applied in the Alfresco Search when finding the space template, the order of this subset can change, and the first element for site-dashboard resulset too. And this is the reason for what I think I could not recreate it exactly.

Relating to your tests, I think also that, if you delete all your templates except aaa-site-dashboard (delete also site-dashboard) and then create a "Collaboration Site", you will obtain a Collaboration Site with aaa-site-dashboard contents inside.

Maybe with =@cm:name syntax in the query, will be enough.

Best regards.

--C.

**Comment by jpotts** [comment]
I see what you are saying now. If any Space Templates contain "site-dashboard" as part of the name and you do not have a Space Template named "site-dashboard", creating a default Collaboration Site will cause the first Space Template that does contain that string to be used as the space template.

The reason it does this is because cm:name is tokenized. There is no way to do an exact match on a tokenized property.

A workaround is to create an empty Space Template named "site-dashboard". This works because that will always be the first one in the list, and the code always picks the first hit.

One fix for the code would be to do a string comparison on the folder name and the sitePreset, rejecting it if they are not an exact match.
